FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# comeet

API documentation for the comeet App and Backend.

## Rooms Collection [/{organization}/rooms]
### List Rooms [GET]
+ Response 200 (application/json)
    + Attributes (array)
        + (room)
        + (room)

## Seacrch Criteria Collection [/{organization}/searchCriteria]
### Seacrch Criteria [GET]
+ Response 200 (application/json)
    + Attributes (array)
        + (city)
        

## Search Rooms Collection [/{organization}/{city}/{roomslist}/rooms]
### Search Rooms [GET]
+ Response 200 (application/json)
    + Attributes (array)
        + (room)
        + (room)

## Book Room Collection [/{organization}/rooms/{room}]
### Search Rooms [POST]
+ Request (application/json)

        { 
            "name" : "Plan architecture for new project",
            "description" : "Let's get together to brainstorm the archteture for the new project"
            "start" : "2017-04-22 16:00:00"
            "start" : "2017-04-22 16:00:00"
            "atendees" :
            [
                "atendee1@exchange.com",
                "atendee2@exchange.com"
            ]
        }
        
+ Response 200 (application/json)

        {
            "success" : true
        }

## Meetings Collection [/{organization}/{user}/meetings]
### List Meetings [GET]
+ Response 200 (application/json)
    + Attributes (array)
        + (meeting)

# Data Structures

## room (object)
+ name: Building 11 (string, required) - User facing string of the room's name
+ email: Bldg11rooms@contoso.com (string, required) - The room's exchange email
+ address: 300 Main St (string) - User facing string address of the meeting room
+ country: USA (string) - User facing country of the meeting room
+ state: WA (string) - User facing state of the meeting room
+ metroarea: Seattle (string) - User facing string of the city or metroarea of the meeting room 
+ latitude: 47.652058 (string) - Latitude of the location of the mmeting room
+ longitude: `-122.355165` (string) - Longitude of the location of the mmeting room
+ capacity: 10 (number) - Maximum number of seated occupants at the meeting room
+ picture: http://www.thelongemonthotels.com/d/longemont/media/optimised_images/Club_Lounge_Meeting_Room.jpg (string) - Picture of the meeting room
+ navigation: http://www.chelseatoronto.com/en/uploads/images/2015/08/deluxe-room-king-new.jpg (string) - map to the meeting room
+ amenities (array[amenity, amenity]) - amenities array for the room
+ freebusy (array[freebusystatus])

## user (object)
+ name: Dairai Nyabando (string, required) - User facing string of the user's name
+ email: dairai@exchange.com (string, required) - The user's exchange email

## meeting (object)
+ subject: Team building exercise (string, required) - User facing string of the meeting's subject
+ body: Let's learn to really work as a team and then have lunch! (string, required) - User facing string of the meeting's body
+ start: `2017-04-22 16:00:00` (string, required) - Start date of the meeting with YYYY-MM-DD HH:MI:Sec format
+ end: `2017-04-22 16:30:00` (string, required) - End date of the meeting with YYYY-MM-DD HH:MI:Sec format
+ location: Conference Room 12 (string) - User facing string of the meeting's location
+ room (room)
+ metingcreator (user)
+ requiredattendees (array[user])
+ optionalattendees (array[user])

## city (object)
+ name: Los Angeles (string, required) - The city name
+ roomslists (array[roomslist,roomslist])

## roomslist (object)
+ name: MainBuilding (string, required) - The rooms list name

##amenity (object)
+ name: projector (string) - name of the projector
+ description: projector with DVI and HDMI

##freebusystatus (object)
+ status: busy (string, required) - status can be busy or free
+ start: `2017-04-22 16:00:00` (string, required) - Start date of the freebusy block with YYYY-MM-DD HH:MI:Sec format
+ end: `2017-04-22 16:30:00` (string, required) - End date of the freebusy block with YYYY-MM-DD HH:MI:Sec format

##sucessstatus (object)
+ success: true (boolean, required) - success status